<?php

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function graphql_translatable_config_pages_translatable_config_pages_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // Custom access check for translatable_config_pages entities.
  // The listed bundles can be viewed by anyone as they don't contain sensitive
  // information.
  $allowed = ['global'];
  return AccessResult::allowedIf($operation === 'view' && in_array($entity->bundle(), $allowed));
}
